### ISSUE TITLE
iPad 2,2 

### ISSUE THREAD

**Issue by tolikes** [zzanehip/Deca5#1]
Error sending iBSS...

**Comment by tolikes** [comment]
@zzanehip 
Last login: Sun Aug  9 18:03:51 on console
/Users/tolikes/Desktop/Deca5.app/Contents/MacOS/Deca5 ; exit;
tolikes@MacBook-Pro-Anatolii ~ % /Users/tolikes/Desktop/Deca5.app/Contents/MacOS/Deca5 ; exit;
/Users/tolikes/Desktop/55/iDeviceReRestore-1/iPad2,2_4.3.3_8J2_Restore.ipsw
Got Path
Entering extract_components
Extracting BuildManifest.plist
Getting Info
iPad2,2 8J2
Entering iBSS
Getting  iBSS Path
Extracting iBSS...
Fetching Key/IV Pair
Decrypting iBSS
decrypt 0 
img3.c:createAbstractFileFromImg3:460: 286e9c4a3e09215adc99f8c7a35700178c34b4d9ac81dda9fc2957912bb728f15a969dc53fd17c5fc82f8c89ed72deb3
iBootPatcher: Starting...
iBootPatcher: iBoot-1072 inputted.
patch_debug_enabled: Entering...
find_dtre_get_value_bl_insn: Entering...
find_dtre_get_value_bl_insn: debug-enabled string is at 0x231f4
find_dtre_get_value_bl_insn: "debug-enabled" xref is at 0x14fc8
find_dtre_get_value_bl_insn: Found LDR R0, ="debug-enabled" at 0x14ac4
find_dtre_get_value_bl_insn: Found BL instruction at 0x14ada
find_dtre_get_value_bl_insn: Leaving...
patch_debug_enabled: Patching BL insn at 0x14ada...
patch_debug_enabled: Leaving...
patch_rsa_check: Entering...
find_rsa_check_4: Entering...
find_rsa_check_4: Found RSA check at 0x1c49c
find_rsa_check_4: Leaving...
patch_rsa_check: Patching RSA at 0x1c49c...
find_ldr_ecid: Entering...
find_ldr_ecid: Found LDR instruction at 0x13ee4
find_ldr_ecid: Found BL ECID at 0x13ef4
find_ldr_ecid: Leaving...
patch_rsa_check: Patching BL ECID at 0x13ef4...
find_ldr_bord: Entering...
find_ldr_bord: Found LDR BORD instruction at 0x13ebe
find_ldr_bord: Found BL BORD at 0x13ed0
find_ldr_bord: Leaving...
patch_rsa_check: Patching BL BORD at 0x13ed0...
find_ldr_prod: Entering...
find_ldr_prod: Found LDR PROD instruction at 0x13dea
find_ldr_prod: Found BL PROD at 0x13dfc
find_ldr_prod: Leaving...
patch_rsa_check: Patching BL PROD at 0x13dfc...
find_ldr_sepo: Entering...
find_ldr_sepo: Found LDR SEPO instruction at 0x13e8c
find_ldr_sepo: Found BL SEPO at 0x13e8e
find_ldr_sepo: Leaving...
patch_rsa_check: Patching BL SEPO at 0x13e8e...
iBootPatcher: Writing out patched file to /Users/tolikes/Library/Application Support/deca5/iBSS.patched...
iBootPatcher: Quitting...
decrypt 0 
img3.c:createAbstractFileFromImg3:460: 286e9c4a3e09215adc99f8c7a35700178c34b4d9ac81dda9fc2957912bb728f15a969dc53fd17c5fc82f8c89ed72deb3
img3.c:createAbstractFileFromImg3:460: 286e9c4a3e09215adc99f8c7a35700178c34b4d9ac81dda9fc2957912bb728f15a969dc53fd17c5fc82f8c89ed72deb3
Entering iBEC
Getting  iBEC Path
Extracting iBEC...
Fetching Key/IV Pair
Decrypting iBEC
decrypt 0 
img3.c:createAbstractFileFromImg3:460: c7ac0cbb5be8a5cad7f1e2a470c8a05605f3f951cb55a2a8e51bba599c799983597ecc6ea573ef74b63f5d146233df62
iBootPatcher: Starting...
iBootPatcher: iBoot-1072 inputted.
patch_boot_args: Entering...
patch_boot_args: Default boot-args string is at 0x2ff68
patch_boot_args: boot-args xref is at 0x14db4
patch_boot_args: Relocating boot-args string...
patch_boot_args: "Reliance on this certificate" string found at 0x35544
patch_boot_args: Pointing default boot-args xref to 0x9ff35544...
patch_boot_args: Applying custom boot-args "-v rd=md0 amfi=0xff cs_enforcement_disable=1 pio-error=0"
patch_boot_args: Found LDR R0, =boot_args at 0x1460a
patch_boot_args: Found CMP R1, #0 at 0x14612
patch_boot_args: Found IT EQ/IT NE at 0x1516a
patch_boot_args: Found MOV R0, R7 at 0x1516c
patch_debug_enabled: Entering...
find_dtre_get_value_bl_insn: Entering...
find_dtre_get_value_bl_insn: debug-enabled string is at 0x300f0
find_dtre_get_value_bl_insn: "debug-enabled" xref is at 0x14e4c
find_dtre_get_value_bl_insn: Found LDR R0, ="debug-enabled" at 0x14950
find_dtre_get_value_bl_insn: Found BL instruction at 0x14966
find_dtre_get_value_bl_insn: Leaving...
patch_debug_enabled: Patching BL insn at 0x14966...
patch_debug_enabled: Leaving...
patch_rsa_check: Entering...
find_rsa_check_4: Entering...
find_rsa_check_4: Found RSA check at 0x1c75c
find_rsa_check_4: Leaving...
patch_rsa_check: Patching RSA at 0x1c75c...
find_ldr_ecid: Entering...
find_ldr_ecid: Found LDR instruction at 0x13d98
find_ldr_ecid: Found BL ECID at 0x13da8
find_ldr_ecid: Leaving...
patch_rsa_check: Patching BL ECID at 0x13da8...
find_ldr_bord: Entering...
find_ldr_bord: Found LDR BORD instruction at 0x13d72
find_ldr_bord: Found BL BORD at 0x13d84
find_ldr_bord: Leaving...
patch_rsa_check: Patching BL BORD at 0x13d84...
find_ldr_prod: Entering...
find_ldr_prod: Found LDR PROD instruction at 0x13c9e
find_ldr_prod: Found BL PROD at 0x13cb0
find_ldr_prod: Leaving...
patch_rsa_check: Patching BL PROD at 0x13cb0...
find_ldr_sepo: Entering...
find_ldr_sepo: Found LDR SEPO instruction at 0x13d40
find_ldr_sepo: Found BL SEPO at 0x13d42
find_ldr_sepo: Leaving...
patch_rsa_check: Patching BL SEPO at 0x13d42...
iBootPatcher: Writing out patched file to /Users/tolikes/Library/Application Support/deca5/iBEC.patched...
iBootPatcher: Quitting...
decrypt 0 
img3.c:createAbstractFileFromImg3:460: c7ac0cbb5be8a5cad7f1e2a470c8a05605f3f951cb55a2a8e51bba599c799983597ecc6ea573ef74b63f5d146233df62
img3.c:createAbstractFileFromImg3:460: c7ac0cbb5be8a5cad7f1e2a470c8a05605f3f951cb55a2a8e51bba599c799983597ecc6ea573ef74b63f5d146233df62
iBootPatcher: Starting...
iBootPatcher: iBoot-1072 inputted.
patch_debug_enabled: Entering...
find_dtre_get_value_bl_insn: Entering...
find_dtre_get_value_bl_insn: debug-enabled string is at 0x300f0
find_dtre_get_value_bl_insn: "debug-enabled" xref is at 0x14e4c
find_dtre_get_value_bl_insn: Found LDR R0, ="debug-enabled" at 0x14950
find_dtre_get_value_bl_insn: Found BL instruction at 0x14966
find_dtre_get_value_bl_insn: Leaving...
patch_debug_enabled: Patching BL insn at 0x14966...
patch_debug_enabled: Leaving...
patch_rsa_check: Entering...
find_rsa_check_4: Entering...
find_rsa_check_4: Found RSA check at 0x1c75c
find_rsa_check_4: Leaving...
patch_rsa_check: Patching RSA at 0x1c75c...
find_ldr_ecid: Entering...
find_ldr_ecid: Found LDR instruction at 0x13d98
find_ldr_ecid: Found BL ECID at 0x13da8
find_ldr_ecid: Leaving...
patch_rsa_check: Patching BL ECID at 0x13da8...
find_ldr_bord: Entering...
find_ldr_bord: Found LDR BORD instruction at 0x13d72
find_ldr_bord: Found BL BORD at 0x13d84
find_ldr_bord: Leaving...
patch_rsa_check: Patching BL BORD at 0x13d84...
find_ldr_prod: Entering...
find_ldr_prod: Found LDR PROD instruction at 0x13c9e
find_ldr_prod: Found BL PROD at 0x13cb0
find_ldr_prod: Leaving...
patch_rsa_check: Patching BL PROD at 0x13cb0...
find_ldr_sepo: Entering...
find_ldr_sepo: Found LDR SEPO instruction at 0x13d40
find_ldr_sepo: Found BL SEPO at 0x13d42
find_ldr_sepo: Leaving...
patch_rsa_check: Patching BL SEPO at 0x13d42...
iBootPatcher: Writing out patched file to /Users/tolikes/Library/Application Support/deca5/iBEC.preboot...
iBootPatcher: Quitting...
decrypt 0 
img3.c:createAbstractFileFromImg3:460: c7ac0cbb5be8a5cad7f1e2a470c8a05605f3f951cb55a2a8e51bba599c799983597ecc6ea573ef74b63f5d146233df62
img3.c:createAbstractFileFromImg3:460: c7ac0cbb5be8a5cad7f1e2a470c8a05605f3f951cb55a2a8e51bba599c799983597ecc6ea573ef74b63f5d146233df62
Entering DeviceTree
Getting  DeviceTree Path
Extracting DeviceTree...
Fetching Key/IV Pair
Decrypting DeviceTree
Entering KernelCache
Getting  KernelCache Path
Extracting KernelCache...
Fetching Key/IV Pair
Decrypting KernelCache
Entering RestoreRamDisk
Getting  RestoreRamDisk Path
Extracting RestoreRamDisk...
Fetching Key/IV Pair
Decrypting RestoreRamDisk
Entering AppleLogo
Getting  AppleLogo Path
Extracting AppleLogo...
Fetching Key/IV Pair
Decrypting AppleLogo
Cleaning Up
Done
Finished

**Comment by tolikes** [comment]
Finished
Attempting to connect... 
Device not in pwned DFU mode.
Finished

**Comment by tolikes** [comment]
but have pwnd dfu

**Comment by zzanehip** [comment]
Check and make sure you have PWND:[checkm8] string in About This Mac->System Report->USB->Apple Mobile Device DFU Mode. It happens to me a lot where Arduino will say device is pwned but it actually isn't.

**Comment by zzanehip** [comment]
As seen here...
<img width="962" alt="Screen Shot 2020-08-09 at 11 19 19 AM" src="https://user-images.githubusercontent.com/40612502/89735680-4f303200-da32-11ea-867c-396be25ca0e0.png">

**Comment by tolikes** [comment]
close issue with kloader
