### ISSUE TITLE
Jailbreak update

### ISSUE THREAD

**Issue by tychoregter** [zzanehip/Deca5#2]
Hi, I were wondering if the update that restores jailbreak functionality is still planned? I also want to thank you for your work! I really appreciate the time and effort you’ve put into this tool, it looks amazing and it works like you’d expect! Thanks again and have a nice day!

**Comment by zzanehip** [comment]
Thanks so much! Update is still planned, in fact, it's nearly done. Plan on releasing it within the next few days...
