### ISSUE TITLE
App crashes on Sending iBEC (iPhone 5 iOS 6.1.3 - macOS Catalina

### ISSUE THREAD

**Issue by alessioacri** [zzanehip/Deca5#3]
I'm gonna leave the crash log here:

>Attempting to connect... 
Packed Img3 image
Detect iBSS/LLB image
Uploading soft DFU
Attempting to connect... 
Attempting to connect... 
Attempting to connect... 
Attempting to connect... 
Attempting to connect... 
Attempting to connect... 
ERROR: Unable to connect to device
ERROR: Unable to connect to device
zsh: segmentation fault  /Users/alessioacri/Downloads/Deca5.app/Contents/MacOS/Deca5

**Comment by zzanehip** [comment]
It looks like your device isn't in pwndfu/isn't properly in pwndfu. Deca5, as of now, doesn't put your iPhone 5 into pwndfu for you. Try using this and then running Deca5 again... https://github.com/dora2-iOS/iPwnder32/releases/tag/1.1

**Comment by LukasMFR** [comment]
Does not work for me (iPhone5c)
