### ISSUE TITLE
PwnDFU Sounds Hard

### ISSUE THREAD

**Issue by Visualwit** [zzanehip/Deca5#7]
I Don't Think I Have The Proper Skill To Use The A5 CheckM8 Method, It Also Looks Too Complicated... Any Other Easy Method???
I Need iOS 7 On My iPhone 4S And iOS 6 On My iPad Mini 1st Generation!

**Comment by Visualwit** [comment]
Anyone???

**Comment by zzanehip** [comment]
uhhh, try coolbooter.
